---
title: "Practica 25 de agosto"
author: "Nahun Antonio Martínez Olmos"
date: "2023-08-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#operaciones
2*(3+4)^2
sqrt(16)

#valor absoluto
abs(-97.6)

x=4

#expresiones logicas
p <- (4<8)
p
q <- -6+4<3&&4!=10  
q
r <- -6+4>3 || 4==10
r
t<-!r
t

#expresiones trigonometricas
sin(pi/6)
cos(pi)

#expresiones logaritmicas
log(3)
log10(8)
logb(16,7)
exp(1) #exponencial
 
q() #esto es para salir de R 


```
# Creación y manejo de vectoras de datos.

```{r}
v<-numeric(3);v

v[3] <- 17;v

#crear un vector asignandole sus valores
x <- c(2,4,3.1,8,6)

is.integer(x)
is.double(x) #modo del vector
length(x)   #longitud del vector

x<-edit(x)

#Vector de valor en el rango especificado
y=1:4;y
y[2]<-5#Modificar el valor

u <- 1:12; u1 
u1 <- u[2*1:5]
u1

#Vecctor numerico utilizando la funcion assign()
assign("z",c(x,0,x))

#Vector numérico generando una sucesion de valores
s1 <- seq(2,10)

s2 <- seq(from=-1, to=5); s2

s3 <- seq(to=2, from=-2); s3

s4 <- seq(from=-3, to=3, by=0.2); s4

s5 <- rep(s3, times=3); s5
```

# Operaciones con vectores numericos

```{r}
x
1/x

v=2*x + z +1;v

#producto interno 
e1 <- c(1,2,3,4); e2 <- c(4,5,6,7); crossprod(e1, e2)

#producto interno
t(e1) %*% e2

#Vector transpuesto
xt <- t(x); xt

u <- exp(y); u

options(digits = 5);u

# Otras operaciones de vectores

resum <- c(length(y),sum(y),prod(y),min(y),max(y)); resum

#ordenamiento de un vector
yo <- sort(y); yo

#Vectores de caracteres
s <- character()

deptos <- c('Santa Ana','Sonsonate','San Salvador'); deptos
deptos[4] <- 'Ahuachapan';deptos

#dar nombres a los elementos de un vector 
codDeptos <- seq(11,14)
names(codDeptos) <- deptos;codDeptos
Occidente <- codDeptos[c('Santa Ana','Ahuachapan')];Occidente

#Crear un vectos con las etiquetas X1, Y2, ... , X9, Y10
etiqs<- paste(c('X','Y'), 1:10, sep=''); etiqs


```

#Creación y manejo de matrices

```{r}
#crear una matriz
M <- matrix(numeric(), nrow = 3, ncol = 4); M

M[1,]<- seq(1,4)

#crear una matriz numerica asignandole todos sus elementos

A <-matrix(c(2,4,6,8,10,12), nrow = 2, ncol = 3);A
mode(A); dim(A); attributes(A); is.matrix(A); is.array(A)

#Matriz creada a partir de un ranfgo de valores
B<-matrix(1:12, nrow = 3, ncol = 4);B

# crear una matriz a partir de 3 vectores

x1<- seq(0,10,2);x1
x2<- seq(1,11,2);x2
x3<- runif(6); x3

#unir 3 vectores en una matriz por columnas
Xcol<-cbind(x1,x2,x3);Xcol

#unir 3 vectores en una matriz por filas
Xfil<-rbind(x1,x2,x3);Xfil

#acceso a filas y columnas de una matriz
X <- Xfil[1:3, c(2,3)]; X 
```

## Operaciones con matrices numéricas

```{r}
# vector por matriz

v<- c(1,2); v %*% A

# matriz por matriz

P<- A %*% B; P

2*A
```
## Operaciones de funciones sobre matrices numéricas

```{r}
#longitud o numero de elementos de la matriz 

length(A)

sqrt(A) # raiz a cada elemento

t(A)

C <- matrix(c(2,1,10,12),ncol = 2, nrow = 2);det(C)

solve(C)

eigen(C)

diag(C)

diag(2:8) #matriz diagonal con los elementos del vector

n<-10
diag(n) # matriz diagonal de dimensiones nxn

A
c(length(A), sum(A), prod(A), min(A), max(A))

O <- matrix(sort(C), nrow = 2, ncol = 2);O


```
## Creación de una matriz de cadenas

```{r}
nombres <- matrix(c('Carlos','José','Ana','René','María','Mario'),
                  nrow = 3, ncol = 2); nombres
```

# Creación de variables indexadas

```{r}
X <- array(c(1,3,5,7,9,11), dim=c(2,3)); X

Z <- array(1,c(3,3)); Z

W <- 2*Z+1; W

TX <- t(X); TX

#producto exterior de dos vectores 

a<- 1:3*2;a
b<- 1:3;b
a;b
M<- a %o% b; M

c <- a*b; c

# matriz de 3 dimensiones (array)

Arreglo3 <- array(c(1:8, 11:18, 111:118), dim= c(2, 4, 3));Arreglo3

# factores nominales

sexo <- c('M','F','F','M','F','F','M')
edad <- c(19, 20, 19, 22, 20, 21, 19)

#Construccion de un factor sexo
FactorSexo = factor(sexo); FactorSexo

#Ver niveles del factor
levels(FactorSexo)

#tabla con la media muestral por categoria sexo
mediaEdad <- tapply(edad, FactorSexo, mean); mediaEdad

is.array(mediaEdad)# es tipo array

#factor ordinal
lugares <- c('Primero', 'Segundo','Tercero','Cuarto','Quinto')
d<- factor(lugares)
ordered(d)
ordered(lugares)

```
## CREACIÓN Y MANEJO DE LISTAS.

```{r}
lista<- list(padre='Pedro', madre='María', no.hijos=3, edad.hijos=c(4,7,9))
is.matrix(lista); is.vector(lista)
lista[[4]][3]
lista['padre']


x<-'padre'; lista[x]

subLista <- lista[4]; subLista

lista[5] <- list(sexo.hijos=c('F','M','F'));lista
lista <- edit(lista)

# modificar una lista con la funcion entry

S <- matrix(c(3, -sqrt(2), -sqrt(2),2), nrow = 2, ncol = 2); S
autovS <- eigen(S); autovS

#autovalores
evals <- eigen(s)$values;evals

#vector de autovalores
autovS$values

#matriz de los autovectores
autovS$vectors

#almacenar solo los autovalores
eval <- eigen(s)$values;eval

#matriz dando nombre a las filas y columnas

Notas <- matrix(c(2,5,7,6,8,2,4,9,10), ncol = 3,
                dimnames = list(c('Matemática','Álgebra','Geometría'),
                                c('Juan','José','René'))); Notas


```
```{r}
log <- sample(c(TRUE,FALSE), size = 20, replace = T); log

#elementos de distr uniforme

comp <- rnorm(20)+runif(20)*(li);comp

num <- rnorm(20, mean=0, sd=1); num

#crear el dataframe con los 3 vectores anteriores 

df1 <- data.frame(log, comp, num); df1

#nombres para los campos del dataframe

nombres <- c('logico','complejo','numerico')

names(df1) <- nombres; df1

#asignarle filas al dataframe

row.names(df1) <- letters[1:20]; df1 
```

## Creación de Dataframe

```{r}
v1<-c(18,21,45,54);v2<-c(150,160,180,205);v3<-c(65,68,65,69);v4<-c('F','M','M','M')

df2 <- data.frame(v1,v2,v3,v4)

colnames(df2)<- c('Edad','Estatura','Peso','Sexo')
row.names(df2)<- 1:4
df2

attach(df2)
search()

Edad

detach(df2)#desconectar el objeto

```